name: Sprawdzanie strony

on: # co 5 minut
  workflow_dispatch:       # umożliwia ręczne uruchomienie

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ustaw Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Wypisz dostępne zmienne środowiskowe
        run: env

      - name: Instaluj zależności
        run: pip install requests beautifulsoup4
      - name: Uruchom skrypt
        run: python check.py
