name: Site Check

on:
  schedule:
    - cron: "*/5 * * * *"   # automatyczne sprawdzanie co 5 minut
  workflow_dispatch:        # ręczne uruchamianie z poziomu GitHuba

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python check_site.py
